import type { Car, Review } from '../types';

export const brands = ['Toyota', 'Honda', 'Kia', 'Mazda', 'Hyundai', 'Mitsubishi', 'Ford', 'VinFast'];
export const categories = ['Sedan', 'Hatchback', 'SUV', 'Pickup', 'MPV', 'EV'];

export const cars: Car[] = [
  {
    id: 'toyota-vios',
    name: 'Toyota Vios',
    brand: 'Toyota',
    category: 'Sedan',
    price: 540000000,
    year: 2024,
    mileage: 1200,
    fuel: 'Petrol',
    seats: 5,
    transmission: 'Automatic',
    horsepower: 107,
    rating: 4.5,
    popularity: 92,
    image: 'https://images.pexels.com/photos/57073/pexels-photo-57073.jpeg?auto=compress&cs=tinysrgb&w=1200',
    gallery: [
      'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/110844/pexels-photo-110844.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    description: 'Xe sedan phổ thông, phù hợp gia đình Việt Nam với nội thất rộng rãi và chi phí sử dụng tiết kiệm.',
    features: ['Tiết kiệm nhiên liệu', 'Trang bị an toàn 7 túi khí', 'Màn hình giải trí 7 inch', 'Hỗ trợ đỗ xe'],
    colors: ['Bạc', 'Trắng', 'Đen'],
    logo: 'Toyota',
    discount: 'Giảm 25 triệu',
    condition: 'Xe mới',
    dealerVerified: true,
  },
  {
    id: 'honda-city',
    name: 'Honda City',
    brand: 'Honda',
    category: 'Sedan',
    price: 570000000,
    year: 2024,
    mileage: 800,
    fuel: 'Petrol',
    seats: 5,
    transmission: 'Automatic',
    horsepower: 119,
    rating: 4.6,
    popularity: 89,
    image: 'https://images.pexels.com/photos/2381069/pexels-photo-2381069.jpeg?auto=compress&cs=tinysrgb&w=1200',
    gallery: [
      'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/121542/pexels-photo-121542.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    description: 'Honda City là lựa chọn phổ thông cho đô thị, vận hành êm và có thiết kế thời trang.',
    features: ['Điều hòa tự động', 'Cruise control', 'Ghế lái chỉnh điện', 'Cảnh báo lệch làn'],
    colors: ['Trắng ngọc', 'Bạc', 'Xanh đen'],
    logo: 'Honda',
    discount: 'Giảm 20 triệu',
    condition: 'Xe mới',
    dealerVerified: true,
  },
  {
    id: 'kia-morning',
    name: 'Kia Morning',
    brand: 'Kia',
    category: 'Hatchback',
    price: 315000000,
    year: 2024,
    mileage: 3400,
    fuel: 'Petrol',
    seats: 5,
    transmission: 'Automatic',
    horsepower: 67,
    rating: 4.4,
    popularity: 95,
    image: 'https://images.pexels.com/photos/373948/pexels-photo-373948.jpeg?auto=compress&cs=tinysrgb&w=1200',
    gallery: [
      'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/110844/pexels-photo-110844.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/121542/pexels-photo-121542.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    description: 'Kia Morning vừa túi tiền, dễ lái và phù hợp với điều kiện giao thông nội thành.',
    features: ['Giá thành hợp lý', 'Khoang hành lý linh hoạt', 'Màn hình giải trí đa phương tiện', 'Hệ thống ABS'],
    colors: ['Đỏ', 'Vàng', 'Bạc'],
    logo: 'Kia',
    discount: 'Giảm 10 triệu',
    condition: 'Xe lướt',
    dealerVerified: true,
  },
  {
    id: 'mazda-cx5',
    name: 'Mazda CX-5',
    brand: 'Mazda',
    category: 'SUV',
    price: 920000000,
    year: 2024,
    mileage: 6200,
    fuel: 'Petrol',
    seats: 5,
    transmission: 'Automatic',
    horsepower: 188,
    rating: 4.7,
    popularity: 86,
    image: 'https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg?auto=compress&cs=tinysrgb&w=1200',
    gallery: [
      'https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/121542/pexels-photo-121542.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    description: 'SUV thịnh hành với kiểu dáng thể thao, nội thất cao cấp và trang bị an toàn đầy đủ.',
    features: ['Cảnh báo điểm mù', 'Cruise control thích ứng', 'Ghế da cao cấp', 'Camera 360 độ'],
    colors: ['Đen', 'Xám', 'Trắng'],
    logo: 'Mazda',
    condition: 'Xe mới',
    dealerVerified: true,
  },
  {
    id: 'mitsubishi-xpander',
    name: 'Mitsubishi Xpander',
    brand: 'Mitsubishi',
    category: 'MPV',
    price: 620000000,
    year: 2024,
    mileage: 9800,
    fuel: 'Petrol',
    seats: 7,
    transmission: 'Automatic',
    horsepower: 102,
    rating: 4.3,
    popularity: 90,
    image: 'https://images.pexels.com/photos/356694/pexels-photo-356694.jpeg?auto=compress&cs=tinysrgb&w=1200',
    gallery: [
      'https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    description: 'Xe 7 chỗ phổ biến cho gia đình Việt Nam, thiết kế rộng rãi và tiện nghi đầy đủ.',
    features: ['Cửa trượt điện', 'Ghế lái chỉnh điện', 'Hệ thống giải trí 9 inch', 'Cảnh báo va chạm'],
    colors: ['Bạc', 'Nâu', 'Đen'],
    logo: 'Mitsubishi',
    condition: 'Xe lướt',
    dealerVerified: true,
  },
  {
    id: 'hyundai-santa-fe',
    name: 'Hyundai Santa Fe',
    brand: 'Hyundai',
    category: 'SUV',
    price: 1090000000,
    year: 2025,
    mileage: 4200,
    fuel: 'Petrol',
    seats: 7,
    transmission: 'Automatic',
    horsepower: 202,
    rating: 4.8,
    popularity: 88,
    image: 'https://images.pexels.com/photos/1149831/pexels-photo-1149831.jpeg?auto=compress&cs=tinysrgb&w=1200',
    gallery: [
      'https://images.pexels.com/photos/121542/pexels-photo-121542.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/254893/pexels-photo-254893.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    description: 'SUV gia đình cao cấp, phù hợp cả đi phố và đi đường dài với tiện nghi 7 chỗ thoải mái.',
    features: ['Cửa khoang hành lý rảnh tay', 'Ghế ngồi thông hơi', 'Hỗ trợ đỗ xe thông minh', 'Đèn LED toàn bộ'],
    colors: ['Xanh đen', 'Trắng', 'Nâu'],
    logo: 'Hyundai',
    discount: 'Giảm 30 triệu',
    condition: 'Xe mới',
    dealerVerified: true,
  },
  {
    id: 'vinfast-vf-e34',
    name: 'VinFast VF e34',
    brand: 'VinFast',
    category: 'EV',
    price: 790000000,
    year: 2024,
    mileage: 5000,
    fuel: 'Electric',
    seats: 5,
    transmission: 'Automatic',
    horsepower: 200,
    rating: 4.2,
    popularity: 84,
    image: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=1200',
    gallery: [
      'https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/272999/pexels-photo-272999.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    description: 'Crossover điện Việt Nam, phù hợp với người dùng cần xe thân thiện môi trường và chi phí vận hành thấp.',
    features: ['Pin 422 km', 'Kết nối thông minh eSIM', 'Hỗ trợ lái bán tự động', 'Sạc nhanh'],
    colors: ['Xanh ngọc', 'Trắng', 'Đen'],
    logo: 'VinFast',
    condition: 'Xe mới',
    dealerVerified: true,
  },
];

export const reviews: Review[] = [
  {
    id: 'review-01',
    author: 'Nguyễn Văn A',
    rating: 5,
    comment: 'Tôi đã được tư vấn rất nhanh, nhân viên nhiệt tình và hỗ trợ đặt lịch lái thử rất chu đáo.',
  },
  {
    id: 'review-02',
    author: 'Trần Thị B',
    rating: 4.8,
    comment: 'Showroom phục vụ chuyên nghiệp, xe mẫu đẹp và giá hợp lý. Tôi rất hài lòng với trải nghiệm mua xe.',
  },
  {
    id: 'review-03',
    author: 'Lê Minh C',
    rating: 4.9,
    comment: 'Giao diện dễ dùng, lọc xe nhanh và đội tư vấn hỗ trợ rõ ràng. Rất phù hợp cho khách hàng mua xe phổ thông.',
  },
];
